Add screenshoots test
Prettier

comparing files

prepare for github

Create separate test matrix for screenshot

delete screenshoots from branch

Prepare test PR

WIP

WIP

Compare one file

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

WIP

simplify, cleanup, allow other SHORT_BRANCHes, keep diffs

No-Issue

WIP

WIP

WIP

WIP

WIP

WIP

WIP

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -21,11 +21,13 @@ jobs:
     env:
       # base of a PR, or pushed-to branch outside PRs, or master
       BRANCH: ${{ github.base_ref || github.ref || 'refs/heads/master' }}
+      UPLOAD_DIFF: false
 
     strategy:
       fail-fast: false
       matrix:
         test:
+        - 'screenshots'
         - 'approval'
         - 'collections'
         - 'ee_controller'
@@ -54,6 +56,18 @@ jobs:
         echo "SHORT_BRANCH=${SHORT_BRANCH}" >> $GITHUB_ENV
         echo "COMPOSE_PROFILE=${COMPOSE_PROFILE}" >> $GITHUB_ENV
         echo "COMPOSE_INTERACTIVE_NO_CLI=1" >> $GITHUB_ENV
+
+    - name: "Set variables for screenshots"
+      if: matrix.test == 'screenshots'
+      run: |
+        UI_COMMIT_MASTER=`curl -s https://api.github.com/repos/ansible/ansible-hub-ui/branches/${SHORT_BRANCH} | jq -r .commit.sha`
+        echo "UI_COMMIT_MASTER=${UI_COMMIT_MASTER}" >> $GITHUB_ENV
+
+        echo ${{ github.event_name }}
+        COMPARE_SCREENSHOTS=${{ github.event_name == 'pull_request' }}
+        echo 'compare screenshots:'
+        echo $COMPARE_SCREENSHOTS
+        echo "COMPARE_SCREENSHOTS=${COMPARE_SCREENSHOTS}" >> $GITHUB_ENV
 
     - name: "Checkout ansible-hub-ui (${{ github.ref }})"
       uses: actions/checkout@v3
@@ -165,6 +179,11 @@ jobs:
       run: |
         npm install
 
+    - name: "Install Imagemagick"
+      if: matrix.test == 'screenshots'
+      run: |
+        sudo apt install imagemagick
+
     - name: "Configure Cypress"
       working-directory: 'ansible-hub-ui/test'
       run: |
@@ -228,6 +247,23 @@ jobs:
       run: |
         diff -Naur <(ls test/cypress/e2e) <(yq '.jobs.cypress.strategy.matrix.test[]' .github/workflows/cypress.yml | sort)
 
+    - name: "Cache master screenshots"
+      if: matrix.test == 'screenshots'
+      uses: actions/cache@v3
+      with:
+        path: ansible-hub-ui/test/screenshots.js/
+        key: screenshots-${{env.SHORT_BRANCH}}-${{ env.UI_COMMIT_MASTER }}
+        restore-keys: |
+          screenshots-${{env.SHORT_BRANCH}}-
+
+    - name: "List cached screenshots"
+      if: ${{ matrix.test == 'screenshots' && env.COMPARE_SCREENSHOTS == 'true' }}
+      continue-on-error: true
+      run: |
+        echo 'Compare screenshots'
+        echo ${{ env.COMPARE_SCREENSHOTS}}
+        ls ansible-hub-ui/test/screenshots.js/
+
     - name: "Run cypress"
       working-directory: 'ansible-hub-ui/test'
       env:
@@ -238,6 +274,55 @@ jobs:
 
         npm run cypress:chrome
 
+    - name: "List new screenshots"
+      if: matrix.test == 'screenshots'
+      continue-on-error: true
+      run: |
+        ls ansible-hub-ui/test/cypress/screenshots/screenshots.js/
+
+    - name: "Compare screenshots"
+      if: ${{ matrix.test == 'screenshots' && env.COMPARE_SCREENSHOTS == 'true' }}
+      working-directory: 'ansible-hub-ui/test'
+      run: |
+        changed=false
+        PR_TITLE="${{ github.event.pull_request.title }}"
+        ACTOR="${{ github.actor }}"
+        echo "$PR_TITLE"
+        echo "$ACTOR"
+        CAN_FAIL=false
+
+        if $(echo $PR_TITLE | grep -q "patternfly") && [ "$ACTOR" = "dependabot[bot]" ]; then
+          echo "can fail on patternfly PRs"
+          CAN_FAIL=true
+        fi
+
+        for orig in screenshots.js/*; do
+          echo $orig
+          new=cypress/screenshots/"$orig"
+          diff=cypress/screenshots/diff--"$(basename "$orig")"
+
+          num=$(compare -metric RMSE "$orig" "$new" "$diff" 2>&1 | awk '{ print $1 }')
+          echo $num
+          num=${num%.*}
+          if [ "$num" -gt 10 ]; then
+            echo "screenshot $orig changed: $num" 1>&2
+            changed=true
+            echo "UPLOAD_DIFF=true" >> $GITHUB_ENV
+          fi
+        done
+
+        if [ "$changed" = true ] && [ CAN_FAIL = true ]; then
+          echo "Process failed because change occured"
+          exit 1
+        fi
+
+    - name: "Move Cache master screenshots"
+      if: ${{ matrix.test == 'screenshots' && env.COMPARE_SCREENSHOTS == 'false' }}
+      working-directory: 'ansible-hub-ui/test'
+      run: |
+        rm -rf screenshots.js/
+        mv cypress/screenshots/screenshots.js/ ./
+
     - uses: actions/upload-artifact@v3
       if: failure()
       with:
@@ -246,6 +331,13 @@ jobs:
           ansible-hub-ui/test/cypress/screenshots
           ansible-hub-ui/test/cypress/videos
 
+    - uses: actions/upload-artifact@v3
+      if: ${{ !failure() && env.UPLOAD_DIFF }}
+      with:
+        name: screenshots_diffs
+        path: |
+          ansible-hub-ui/test/cypress/screenshots
+          
     - name: "Kill container, show debug info"
       if: always()
       working-directory: 'oci_env'
